.PHONY: clean All

All:
	@echo "----------Building project:[ singleton8_2 - Debug ]----------"
	@cd "singleton8_2" && "$(MAKE)" -f  "singleton8_2.mk"
clean:
	@echo "----------Cleaning project:[ singleton8_2 - Debug ]----------"
	@cd "singleton8_2" && "$(MAKE)" -f  "singleton8_2.mk" clean
